### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by zacharyhenry** [AuraDevelopmentTeam/JustEnoughReactors#10]
Who do I talk to about how to make a extreme reactor work

Minecraft  v 1.12.2

Forge v 14.23.5.2838

Extreme reactors v .4.5.67

**Comment by zacharyhenry** [comment]
I cant show any pics because my internet is down

**Comment by zacharyhenry** [comment]
I figured it out
gellis 12 I never done this mod before ok

**Comment by BrainStone** [comment]
For future reference, this is just the JEI Addon for Extreme Reactors.
