### ISSUE TITLE
RU Translation and sentence

### ISSUE THREAD

**Issue by MrLador** [AuraDevelopmentTeam/JustEnoughReactors#3]
RU Translation: [https://drive.google.com/](https://drive.google.com/open?id=1Xs4assEkb48YiZwRfejgO8rs-dsBBI-H)
1.You can create a small animation of the construction of the reactor.
2.What is that liquid that cools the reactor.

**Comment by BrainStone** [comment]
First of all thank you for the translation! But it has already been added through #2. 

However I’m not entirely sure what you mean with the animation.

And what materials and fluids can be used inside the reactor is planned to be added soon.

**Comment by MrLador** [comment]
I meant a little animation of building a reactor, as is in the book about Tinkers Construct (Furnace).

**Comment by BrainStone** [comment]
I think that's a little out of the scope of this project. I might do it later, but for now I'll close it.
