### ISSUE TITLE
Can’t find yellorite in deep dark (extra utilities)

### ISSUE THREAD

**Issue by SaadTheGlad** [AuraDevelopmentTeam/JustEnoughReactors#6]
Hello. I cannot find any yellorite in the deep dark (extra utilities) I know this isn’t related to the texture pack but I couldn’t find in repertoire thing related to this subject. I haven’t tried searching the overworld but I thought somebody would help me.

P.S I used world edit to clear out the stone but I don’t know how to scan for ores.

**Comment by BrainStone** [comment]
The correct repo is https://github.com/ZeroNoRyouki/BigReactors/issues
