### ISSUE TITLE
Missing most of the JEI tabs

### ISSUE THREAD

**Issue by miiichael** [AuraDevelopmentTeam/JustEnoughReactors#8]
Apart from the Reactor Fuel tab being present with Cyanite, all of the JER tabs seem to be AWOL.

![2019-04-11_23 07 00](https://user-images.githubusercontent.com/4179353/55968467-9bd4f300-5cae-11e9-9a1c-73b70298f91a.png)
![2019-04-11_23 10 15](https://user-images.githubusercontent.com/4179353/55968678-1140c380-5caf-11e9-8643-a62d934e10dd.png)

Mod versions: forge-1.12.2-14.23.5.2768, zerocore-1.12.2-0.1.2.8, jei_1.12.2-4.15.0.268, ExtremeReactors-1.12.2-0.4.5.65, JustEnoughReactors-1.12.2-1.1.3.61.

Platform: openjdk 8u212-b01-1 on Debian stretch, amd64.

See also [debug.log](https://github.com/AuraDevelopmentTeam/JustEnoughReactors/files/3069255/debug.log). I'm suspicious of the "Unable to lookup..." errors, but you will know better than I.

**Comment by BrainStone** [comment]
Alright, sorry for the late response. From the looks of it, the version of JEI I used for it is too old.

And sorry for it being so late. Live got me busy...

**Comment by BrainStone** [comment]
I can't seem to replicate that issue. The logs say nothing...

Try clicking on the box that says crafting in your screenshots. That should show all categories.

**Comment by miiichael** [comment]
Yes, all three tabs show up in the "all recipes" list:
![2019-04-23_20 20 06](https://user-images.githubusercontent.com/4179353/56580520-4c26ed80-6605-11e9-94bd-34b324667031.png)

But don't show up when viewing recipes for a specific item:
![2019-04-23_20 20 20](https://user-images.githubusercontent.com/4179353/56580544-5cd76380-6605-11e9-96f6-b367746ed584.png)

Above screenshots generated from a minimal pack with forge-1.12.2-14.23.5.2768, jei_1.12.2-4.15.0.268, zerocore-1.12.2-0.1.2.8, ExtremeReactors-1.12.2-0.4.5.65, JustEnoughReactors-1.12.2-1.1.3.61.

**Comment by BrainStone** [comment]
That’s because in the example you pressed `R` for recipe. Try `U` for usage.
