### ISSUE TITLE
its not letting me use ur mod it keeps saying big reactors missing and i got the latest version installed

### ISSUE THREAD

**Issue by zacharyhenry** [AuraDevelopmentTeam/JustEnoughReactors#9]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.  
Also please remove anything that doesn't apply! If you're making a feature request or suggestion, just delete this.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- JustEnoughResources:
- Forge:
- Other related mods:

#### Your most recent log or stack trace file where the issue was present:

[pastebin/gist/etc link here]

```
[Or stack trace here (Remove this if you don't put anything here!)]
```

**Comment by zacharyhenry** [comment]
version 1.12.2
forge 14.23.5.2838
[1.12.2latest.log](https://github.com/AuraDevelopmentTeam/JustEnoughReactors/files/3204946/1.12.2latest.log)

**Comment by BrainStone** [comment]
Make sure you have Extreme Reactors installed. 
And if you think you do, try staring without Just Enough Reactors and see if Extreme Reactors loads.

And for the future, please fill out the form provided. And it would be nice if you could still do that (you can edit the post).

**Comment by zacharyhenry** [comment]
I fixed it but it crashes when loading thru forge

**Comment by BrainStone** [comment]
Crash log?

**Comment by zacharyhenry** [comment]
I found the problem  ) 

Some how it downloaded big reactor in my mods folder and it was crashing the forge startup

**Comment by BrainStone** [comment]
And for future reference, Extreme Reactors is called `bigreactors` internally. Though it needs to be Extreme Reactors.
